version: '3.9'
services:
  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql_database:5432/teste
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  postgres:
    image: postgres
    container_name: psql_database
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teste
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    networks:
      - spring-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data

networks:
  spring-network:
volumes:
  postgres-volume:
